# Site settings
title: A dotNET Soul in a OS X Env
email: kristofer@linnestjerna.se
description: > # this means to ignore newlines until "baseurl:"
  A dotNET programmers diary when building, configuring, coding and trying out new stuff in the land of Darwin with dotNET on his mind
  This site is meant to be an aid when in doubt...if this is the correct path to walk.
 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://krippz.github.io" # the base hostname & protocol for your site
twitter_username: krippz
github_username:  krippz

# Build settings
markdown: kramdown
